//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveFitnessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance : System.ComponentModel.INotifyPropertyChanged
    {
    
     #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
    
        private int _ClientId;
     public int ClientId 
     { 
      get
      {
       return _ClientId;
      } 
      set
      {
       if(_ClientId != value)
       {
        _ClientId = value;
        OnPropertyChanged("ClientId");
       }
      }
     }
     
        private System.DateTime _DateVisit;
     public System.DateTime DateVisit 
     { 
      get
      {
       return _DateVisit;
      } 
      set
      {
       if(_DateVisit != value)
       {
        _DateVisit = value;
        OnPropertyChanged("DateVisit");
       }
      }
     }
     
        private string _Payment;
     public string Payment 
     { 
      get
      {
       return _Payment;
      } 
      set
      {
       if(_Payment != value)
       {
        _Payment = value;
        OnPropertyChanged("Payment");
       }
      }
     }
     
        private Nullable<float> _AttendancePrice;
     public Nullable<float> AttendancePrice 
     { 
      get
      {
       return _AttendancePrice;
      } 
      set
      {
       if(_AttendancePrice != value)
       {
        _AttendancePrice = value;
        OnPropertyChanged("AttendancePrice");
       }
      }
     }
     
    
        private Client _Client;
     public virtual Client Client 
     { 
      get
      {
       return _Client;
      } 
      set
      {
       if(_Client != value)
       {
        _Client = value;
        OnPropertyChanged("Client");
       }
      }
     }
     
    }
}
